import React from 'react';


const Home = () => {
    return (
        <div>
            <h2>Description du site</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae veritatis, voluptatum ducimus laborum doloremque quam et minus atque, non nostrum quidem asperiores, at tenetur enim dolor. Voluptatum voluptate eius minima corporis commodi iure vitae natus, eum quibusdam veritatis vero officia aperiam tempore repudiandae cumque quisquam impedit, harum enim modi? Omnis architecto vero vel? Quidem perspiciatis dignissimos incidunt eos eaque, magni animi vel odio, deserunt, laborum ex adipisci! Quae eos natus possimus, quod debitis placeat! Sapiente voluptatem distinctio reiciendis veritatis, nulla error dicta sit perspiciatis magnam vel, ex repudiandae. Maxime perferendis harum excepturi, recusandae deleniti consequuntur totam? Beatae aliquid, nam suscipit debitis neque voluptate, sint eligendi illum sit eveniet doloremque. Voluptates error iste sint repellendus reiciendis rerum, blanditiis vero nemo enim dignissimos quasi libero quidem, unde mollitia facere nesciunt eaque fuga ullam odio. Nemo autem repellat nisi laboriosam dignissimos officia fuga! Natus distinctio, dolorem reprehenderit quod quaerat, odio nemo incidunt, esse ipsam nulla porro. Asperiores incidunt molestias voluptate voluptates repudiandae odio voluptatum doloribus exercitationem, aspernatur dolorem ullam cumque possimus accusamus, odit sequi dicta totam quibusdam sed itaque! Quis sunt placeat, voluptatum facilis quos, tempora corporis consectetur voluptate eveniet, iure sed. Accusamus delectus dolores odit ullam aliquid amet explicabo facere porro. Possimus officiis eos, dicta quod quas iusto adipisci tempora eius qui neque cupiditate cumque amet! Mollitia cumque, iste cupiditate similique nemo adipisci voluptatem quisquam quam, quaerat dolore corporis sapiente, voluptatibus neque. Labore architecto ab soluta perspiciatis assumenda ipsa asperiores dolor repudiandae modi officia necessitatibus iste, dolores est nisi deserunt dolorum excepturi! Sit est voluptatibus at, perferendis, officiis earum soluta error provident fugit tempora minus! Ex obcaecati accusamus magni maxime fugit labore perferendis? Expedita nostrum illum, sint odit pariatur reprehenderit tenetur veniam, distinctio temporibus error, facilis quam praesentium nulla dolore ratione natus odio enim eum? Distinctio in eum dolores, ab quod illo.</p>
        </div>
    );
};

export default Home;